### ISSUE TITLE
Little GPU-util

### ISSUE THREAD

**Issue by mtk380** [ericyinyzy/MTN_trajectory#2]
I check the gpu-util when I run the code, while it reminds 4%?

**Comment by ericyinyzy** [comment]
Hi!

Thanks for asking. 
It's really a problem, I have verified.

It may be triggered by the following reasons:
1. Code issue. There are some data preprocessing steps in the training and validation function, thus leading to low efficiency on GPUs. **This part will be optimized in the next version.**
2. Model size. The model size is small and with few parameters. Codes only occupy a small portion of resources and computation time on GPUs.
