### ISSUE TITLE
Fine-graind fusion issue

### ISSUE THREAD

**Issue by Serenfang** [ericyinyzy/MTN_trajectory#3]
I noticed that you used a frame of 45 for fine-grained processing, but the input length for optical flow data is 14. Shouldn't you enter a length of '45-1'?
the code: enc_extra_ped = ped_op_flow[:, :(inp_l - 1)].reshape(ped_op_flow.shape[0], 2 * (inp_l - 1), -1).to(device)

**Comment by ericyinyzy** [comment]
Sorry for the late response. 45 is the length of predicted positions, and 15 is the length of input positions (only containing 14 frames of optical flow).  enc_extra_ped here is the input, and the network does not use the optical flow after the last observed frame.

**Comment by Serenfang** [comment]
Thank you for answering my question. I have a few more questions. Why not use frame 15 optical flow data as input? Isn't the optical flow data of frame 15 still historical for the predicted data of frame 45?

**Comment by Serenfang** [comment]
If I USE FRAME 15 optical FLOW DATA DURING TRAINING, IS it wrong? I'm still confused about how optical flow data is used.

**Comment by ericyinyzy** [comment]
Frame 1 optical flow is extracted between the 1st and 2nd images, Frame 2 optical flow is extracted between the 2nd and 3rd images.......Frame 14 optical flow is extracted between the 14th and 15th images. The question here is: Given 15 images and target pedestrians' bounding boxes, predict 45 bounding boxes in the next 45 frames (16th-60th).

If you use Frame 15 optical flow, you will need the 15th image and 16th image, however, you don't have the 16th image.

**Comment by Serenfang** [comment]
Thank you very much for your answer. I already understand how optical flow data is used.
