### ISSUE TITLE
How to visualize trajectories？ as the result in your paper

### ISSUE THREAD

**Issue by Alex-fishred** [ericyinyzy/MTN_trajectory#5]

**Comment by zehranrgi** [comment]
any update?

**Comment by ericyinyzy** [comment]
Sorry for the late reply. Thank you for being interested in our work!  The GitHub repository does not contain a  displaying code now. You can do it by yourself. After you get the trajectory prediction results,  denormalize the prediction to the original image space. We draw the generated trajectory on the first frame, and only the first and last bounding boxes are displayed.
