### ISSUE TITLE
Images / Data Loader

### ISSUE THREAD

**Issue by MZ82020** [ericyinyzy/MTN_trajectory#6]
Hello, 
You don't use images in your approach please? How did you get it from videos and where is the file of images obtained in this case please?

Another question, I don't really understand your data Loader! Can you give more details please? 

Thanks!

**Comment by ericyinyzy** [comment]
We use images to capture optical flow for prediction. Images are extracted from videos by [python codes](https://www.geeksforgeeks.org/extract-images-from-video-in-python/). We didn't upload split images. You can do it by yourself.  For data loader, can you elaborate more on the question? For example, which part did you not understand?
